apiVersion: v1
kind: Service
metadata:
  name: shopping-api
  namespace: shopping-api-3a1d28688f3bd17eb864e127b1a20653
  labels:
    app: shopping-api
    service: shopping-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    service: shopping-api
  