apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shopping-api-3a1cab7a0110890cf10d72409ba5d1c6
  name: shopping-api
  labels:
    app: shopping-api
    project-id: shopping-api-3a1c99d4-3818-cbbc-53fa-79addc57819f
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      service: shopping-api
      project-id: shopping-api-3a1c99d4-3818-cbbc-53fa-79addc57819f
  template:
    metadata:
      labels:
        app: shopping-api
        service: shopping-api
        project-id: shopping-api-3a1c99d4-3818-cbbc-53fa-79addc57819f
      annotations:
        vault.hashicorp.com/agent-inject: 'false'
    spec:
      serviceAccountName: shopping-api
      imagePullSecrets:
      - name: shopping-api-registry-secret
      
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: shopping-api
          image: docker.io/cahityusuf/shopping-api:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              exec dotnet Shopping.API.dll
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - FOWNER
                - SETGID
                - SETUID
          resources:
            requests:
              memory: 1Gi
              cpu: 2
            limits:
              memory: 1Gi
              cpu: 2     
          
             