apiVersion: v1
kind: Service
metadata:
  name: shopping-api
  namespace: shopping-api-3a1cac972c6742b1d71b67974b2707fe
  labels:
    app: shopping-api
    service: shopping-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    service: shopping-api
  