apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: featureflag
  namespace: argocd
spec:
  description: Project for featureflag
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

