apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shopping-api
  namespace: shopping-api-3a1dee2d8edac3acbb90136b232373c8
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopping-api
  maxReplicas: 3
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70