apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-client-config
  namespace: shopping-client-3a1cdc1953be0abb6fc23c40f425857c
data:
  deneme2: "test2"
  deneme3: "false"
  deneme4: "cahit,yusuf"