apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shopping-client-3a1cdbf2d9c4ee8c2a94bb7f3f88912d
  name: shopping-client
  labels:
    app: shopping-client
    project-id: shopping-client-3a1cdbf2-d96d-78bd-aa21-df8854f6edbd
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      service: shopping-client
      project-id: shopping-client-3a1cdbf2-d96d-78bd-aa21-df8854f6edbd
  template:
    metadata:
      labels:
        app: shopping-client
        service: shopping-client
        project-id: shopping-client-3a1cdbf2-d96d-78bd-aa21-df8854f6edbd
      annotations:
        vault.hashicorp.com/agent-inject: 'false'
    spec:
      serviceAccountName: shopping-client
      imagePullSecrets:
      - name: shopping-client-registry-secret
      
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: shopping-client
          image: docker.io/cahityusuf/shopping-client:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              exec dotnet Shopping.Client.dll
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - FOWNER
                - SETGID
                - SETUID
                - DAC_OVERRIDE
                - FSETID
                - NET_BIND_SERVICE
          resources:
            requests:
              memory: 512Mi
              cpu: 0.5
            limits:
              memory: 512Mi
              cpu: 0.5     
          
             