apiVersion: apps/v1
kind: Deployment
metadata:
  name: featureflag
  namespace: featureflag
spec:
  template:
    spec:
      containers:
      - name: featureflag
        readinessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          tcpSocket: 
          exec: 
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          tcpSocket: 
          exec: 
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe: 
