apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopping-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com:443/cahityusuf/devopszon.git
    targetRevision: HEAD
    path: ./shopping-api/base
  destination:
    server: https://kubernetes.default.svc
    namespace: shopping-api-3a1cac972c6742b1d71b67974b2707fe
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true