apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: shopping-web
  namespace: argocd
spec:
  description: Project for shopping-web
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

